# Generated by Django 2.1.1 on 2021-06-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appF', '0002_auto_20210615_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
