# Generated by Django 2.1.1 on 2021-06-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG', '0002_auto_20210617_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
